# Generated by Django 5.0.1 on 2025-11-28 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tax_id'], name='companies_tax_id_cd19d0_idx'), models.Index(fields=['is_active'], name='companies_is_acti_e9a12b_idx')],
            },
        ),
    ]
