# Generated by Django 5.0.1 on 2025-11-28 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('vehicle', 'Vehículo'), ('employee', 'Empleado'), ('supplier', 'Proveedor'), ('asset', 'Activo')], max_length=50, verbose_name='Tipo de entidad')),
                ('entity_code', models.CharField(max_length=100, verbose_name='Código')),
                ('entity_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'entity_type'], name='entities_company_48210f_idx'), models.Index(fields=['entity_code'], name='entities_entity__17cd94_idx'), models.Index(fields=['is_active'], name='entities_is_acti_222b29_idx')],
                'unique_together': {('company', 'entity_type', 'entity_code')},
            },
        ),
    ]
