# Generated by Django 5.0.1 on 2025-11-28 17:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('requires_issue_date', models.BooleanField(default=False, verbose_name='Requiere fecha de emisión')),
                ('requires_expiration_date', models.BooleanField(default=False, verbose_name='Requiere fecha de vencimiento')),
                ('uses_n8n_workflow', models.BooleanField(default=False, verbose_name='Usa N8N')),
                ('n8n_webhook_url', models.CharField(blank=True, max_length=512, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL Webhook N8N')),
                ('entity_type', models.CharField(choices=[('vehicle', 'Vehículo'), ('employee', 'Empleado'), ('supplier', 'Proveedor'), ('asset', 'Activo')], max_length=50, verbose_name='Tipo de entidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'document_types',
                'ordering': ['entity_type', 'name'],
                'indexes': [models.Index(fields=['code'], name='document_ty_code_45b0b5_idx'), models.Index(fields=['entity_type'], name='document_ty_entity__cba31e_idx'), models.Index(fields=['is_mandatory'], name='document_ty_is_mand_733465_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('file_size', models.BigIntegerField(verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('s3_bucket', models.CharField(max_length=255, verbose_name='Bucket S3')),
                ('s3_key', models.CharField(max_length=512, verbose_name='Clave S3')),
                ('s3_region', models.CharField(max_length=50, verbose_name='Región S3')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('validation_status', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1, verbose_name='Estado de validación')),
                ('validation_reason', models.TextField(blank=True, null=True, verbose_name='Razón de validación')),
                ('uploaded_by', models.CharField(max_length=255, verbose_name='Subido por')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='Empresa')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entities.entity', verbose_name='Entidad')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('uploaded', 'Cargado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('n8n_sent', 'Enviado a N8N'), ('n8n_callback', 'Respuesta de N8N')], max_length=50, verbose_name='Acción')),
                ('previous_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=1, verbose_name='Nuevo estado')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Razón')),
                ('performed_by', models.CharField(max_length=255, verbose_name='Realizado por')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Log de Validación',
                'verbose_name_plural': 'Logs de Validación',
                'db_table': 'document_validation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company'], name='documents_company_fa64b9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity'], name='documents_entity__ab59f4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_0426e4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['validation_status'], name='documents_validat_cc093b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiration_date'], name='documents_expirat_e43349_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('validation_status__in', ['P', 'A', 'R'])), name='valid_validation_status'),
        ),
        migrations.AddIndex(
            model_name='documentvalidationlog',
            index=models.Index(fields=['document'], name='document_va_documen_f07ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentvalidationlog',
            index=models.Index(fields=['action'], name='document_va_action_6501db_idx'),
        ),
        migrations.AddIndex(
            model_name='documentvalidationlog',
            index=models.Index(fields=['created_at'], name='document_va_created_7a335b_idx'),
        ),
    ]
