# Generated by Django 5.0.1 on 2025-11-30 19:32

import os
from django.db import migrations
from django.conf import settings


def create_validation_function(apps, schema_editor):
    """Create the PL/pgSQL validation function."""
    # Get the path to the SQL file
    sql_file_path = os.path.join(
        settings.BASE_DIR.parent,
        'sql',
        'fn_validate_documents_bulk.sql'
    )

    # Read and execute the SQL file
    with open(sql_file_path, 'r', encoding='utf-8') as f:
        sql = f.read()
        schema_editor.execute(sql)


def drop_validation_function(apps, schema_editor):
    """Drop the PL/pgSQL validation function."""
    schema_editor.execute(
        "DROP FUNCTION IF EXISTS fn_validate_documents_bulk(UUID, VARCHAR, UUID[]);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_validation_function,
            reverse_code=drop_validation_function
        ),
    ]
